"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_user_bg)\
$os\
$username\
[](bg:color_dir fg:color_user_bg)\
$directory\
[](fg:color_dir bg:color_langgreen)\
$git_branch\
$git_status\
[](fg:color_langgreen bg:color_lang)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_lang bg:color_bg3)\
$docker_context\
$conda\
[](fg:color_bg3 bg:color_bg1)\
$time\
[ ](fg:color_bg1)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_lang = '#7AA89F'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_langgreen = '#947FB8'
color_sand = '#D7D3AB'
color_yellow = '#ECFF00'
color_user_bg = '#E5C384'
color_dir = '#FE5D62'
color_black = '#000000'
color_white = '#FFFFFF'

[os]
disabled = false
style = "bg:color_user_bg fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "🍙"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:color_user_bg fg:color_black"
style_root = "bg:color_user_bg fg:color_black"
format = '[ $user ]($style)'

[directory]
style = "fg:color_black bg:color_dir"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_langgreen"
format = '[[ $symbol $branch ](fg:color_black bg:color_langgreen)]($style)'

[git_status]
style = "bg:color_langgreen"
format = '[[($all_status$ahead_behind )](fg:color_black bg:color_langgreen)]($style)'

[nodejs]
symbol = ""
style = "bg:color_lang"
format = '[[ $symbol( $version) ](fg:color_black bg:color_lang)]($style)'

[c]
symbol = " "
style = "bg:color_lang"
format = '[[ $symbol( $version) ](fg:color_black bg:color_lang)]($style)'

[rust]
symbol = ""
style = "bg:color_lang"
format = '[[ $symbol( $version) ](fg:color_black bg:color_lang)]($style)'

[golang]
symbol = ""
style = "bg:color_lang"
format = '[[ $symbol( $version) ](fg:color_black bg:color_lang)]($style)'

[php]
symbol = ""
style = "bg:color_lang"
format = '[[ $symbol( $version) ](fg:color_black bg:color_lang)]($style)'

[java]
symbol = " "
style = "bg:color_lang"
format = '[[ $symbol( $version) ](fg:color_black bg:color_lang)]($style)'

[kotlin]
symbol = ""
style = "bg:color_lang"
format = '[[ $symbol( $version) ](fg:color_black bg:color_lang)]($style)'

[haskell]
symbol = ""
style = "bg:color_lang"
format = '[[ $symbol( $version) ](fg:color_black bg:color_lang)]($style)'

[python]
symbol = ""
style = "bg:color_lang"
format = '[[ $symbol( $version) ](fg:color_black bg:color_lang)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[conda]
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)]($style)'

[time]
disabled = true
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_langgreen)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
